apiVersion: memorydb.services.k8s.aws/v1alpha1
kind: Snapshot
metadata:
  name: $SNAPSHOT_NAME
spec:
  clusterRef:
    from:
      name: $CLUSTER_NAME
  kmsKeyID: $KMS_KEY_ID
  name: $SNAPSHOT_NAME
  tags:
    - key: $SNAPSHOT_TAG_KEY
      value: $SNAPSHOT_TAG_VALUE